package it.develhope.TestCrud.entities;

import jakarta.persistence.*;

/**
 * @author Drumstyle92
 * Class representing a student entity with various attributes
 */
@Entity
@Table
public class Student {

    /**
     * primary key of the entity that will be automatically generated by the database
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * Represents the student's name
     */
    @Column
    private String name;

    /**
     * Represents the student's surname
     */
    @Column
    private String surname;

    /**
     * Represents the student's job status
     */
    @Column(name = "is_working")
    private boolean isWorking;

    /**
     * Default constructor
     */
    public Student(){}

    /**
     * @param id        the id
     * @param name      the name
     * @param surname   the surname
     * @param isWorking the is working
     * Parameterized constructor
     */
    public Student(Long id, String name, String surname, boolean isWorking) {

        this.id = id;
        this.name = name;
        this.surname = surname;
        this.isWorking = isWorking;

    }

    /**
     * @return the id
     * Encapsulation method
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id the id
     * Encapsulation method
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return the name
     * Encapsulation method
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name
     * Encapsulation method
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the surname
     * Encapsulation method
     */
    public String getSurname() {
        return surname;
    }

    /**
     * @param surname the surname
     * Encapsulation method
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     * @return the boolean
     * Encapsulation method
     */
    public boolean isWorking() {
        return isWorking;
    }

    /**

     * @param working the working
     * Encapsulation method
     */
    public void setWorking(boolean working) {
        isWorking = working;
    }

}
